server:
  port: 8586
management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: health
spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: 'mongodb://mongodb:27017/test'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/